Component parser
JaverSingleton/bdui pull request #1
Opened 2022-11-22 18:25 UTC by solkin

2022-11-23 10:05 UTC, JaverSingleton requested changes

2022-11-23 10:05 UTC, JaverSingleton commented on core/src/main/java/ru/javersingleton/bdui/core/BeduinController.kt
> +    components: ComponentsCache,
Коль ты уже начал прокидывать что-то, может давай тогда прокидывать сюда Context? Так будет понятнее, в ином случае мы его тут создаём, что неправильно.
В идеале Context должен набираться пользователем библиотеки при первичной инициализации и использоваться при создании любой Beduin view

2022-11-23 10:05 UTC, JaverSingleton commented on core/src/main/java/ru/javersingleton/bdui/core/ComponentsCache.kt
> +    fun put(type: String, component: MetaComponentBlueprint)
Надо подумать над способом хранение этих блюпринтов.
Тут ты его уже распарсил, а для хранения его получается вновь придётся во что-то превратить, может сюда лучше JSON?

2022-11-23 11:59 UTC, solkin commented on core/src/main/java/ru/javersingleton/bdui/core/BeduinController.kt
> +    components: ComponentsCache,
`Context` предполагается общий для жизненного цикла приложения между различными сценариями BDUI?

2022-11-24 12:34 UTC, JaverSingleton approved these changes

2022-11-24 16:48 UTC, merged