Add calculator sample; add some functions; add layout_weight support;…
JaverSingleton/bdui pull request #41
Opened 2023-02-01 16:33 UTC by solkin

Add calculator sample
Add some functions
Add layout_weight support
Add radio card group sample

2023-02-02 07:25 UTC, Subtle-fox approved these changes

2023-02-02 07:25 UTC, Subtle-fox commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/DivideFunction.kt
> +                val value1: PrimitiveData = params.prop("value1").current()!!
Предлагаю ввести метод `requreProperty(name): PrimitiveData = prop(name).current()!!`
Код станет чище тут и в похожих местах, раз такая конструкция используется часто

2023-02-02 07:25 UTC, Subtle-fox commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/WhenFunction.kt
> +                    ?.asString()
nit: `orEmpty()`

2023-02-02 07:25 UTC, Subtle-fox commented on samples/src/main/java/ru/javersingleton/bdui/samples/assets/Calculator.kt
> +val calculator = "calculator.json" to """
🔥

2023-02-02 07:49 UTC, JaverSingleton commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/DivideFunction.kt
> +                val value1: PrimitiveData = params.prop("value1").current()!!
Плюсую
Только `requireProperty`)

2023-02-02 08:01 UTC, JaverSingleton requested changes

2023-02-02 13:02 UTC, Subtle-fox commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/DivideFunction.kt
> +                val value1: PrimitiveData = params.prop("value1").current()!!
`requireValue ( propertyName )` ?

2023-02-02 13:04 UTC, Subtle-fox commented on samples/src/main/java/ru/javersingleton/bdui/samples/assets/Calculator.kt
> +val calculator = "calculator.json" to """
Кроссплатформенной библиотеки io от jetbrains нет. Поэтому либо на каждой платформе своё, либо текущий вариант (по мне - так вполне рабочий для примеров)

2023-02-02 15:07 UTC, solkin commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/SubstringFunction.kt
> +                        ).validateStart(value.length)
Там не только min/max, там есть логика, поэтому вынес её в отдельную функцию валидации.

2023-02-02 15:08 UTC, solkin commented on function/base/src/commonMain/kotlin/ru/javersingleton/bdui/function/base/SubstringFunction.kt
> +                        ).validateStart(value.length)
Так оно и было сначала, но решил завернуть в одну. Разделил обратно на две.

2023-02-02 15:09 UTC, solkin commented on component/column/android-view/src/main/java/ru/javersingleton/bdui/component/column/compose/ColumnComponent.kt
> +                if (item.params.weight > 0) {
Оставил со ссылкой на официальную доку

2023-02-06 08:45 UTC, JaverSingleton approved these changes

2023-02-06 17:01 UTC, merged